spring:
  application:
    name: api-gateway
  # Reactive WebFlux is enabled by using spring-boot-starter-webflux.
  # threads:
  #   virtual:
  #     enabled: true
  config:
    import: "optional:configserver:http://localhost:8888"

jwt:
  secret: "asa@T#&@#^&7847587SAD23HSG&$#^%DH8496584"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true