spring:
  application:
    name: api-gateway
  # Reactive WebFlux is enabled by using spring-boot-starter-webflux.
  # threads:
  #   virtual:
  #     enabled: true
  config:
    import: "optional:configserver:http://localhost:8888"
  redis:
    host: localhost
    port: 6379

server:
  port: 8080

jwt:
  secret: "asa@T#&@#^&7847587SAD23HSG&$#^%DH8496584"
  header: Authorization
  token-prefix: Bearer

gateway:
  public-paths: /api/auth/**,/actuator/**
  rate-limit:
    free-per-minute: 100
    premium-per-minute: 1000

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus
  endpoint:
    health:
      show-details: always
